### ISSUE TITLE
Work just on linux ?

### ISSUE THREAD

**Issue by nailuyx** [EntySec/RomBuster#13]
**I've tried everything, but its seems that its not gonna work, I wanna know if its not working on windows !**
PS C:\Users\Nailuy> rombuster
Traceback (most recent call last):
  File "\\?\C:\Users\Nailuy\AppData\Local\Programs\Python\Python312\Scripts\rombuster-script.py", line 33, in <module>
    sys.exit(load_entry_point('rombuster==1.0.0', 'console_scripts', 'rombuster')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\?\C:\Users\Nailuy\AppData\Local\Programs\Python\Python312\Scripts\rombuster-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nailuy\AppData\Local\Programs\Python\Python312\Lib\importlib\metadata\__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nailuy\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Nailuy\AppData\Local\Programs\Python\Python312\Lib\site-packages\rombuster-1.0.0-py3.12.egg\rombuster\__init__.py", line 25, in <module>
    from .__main__ import RomBuster
  File "C:\Users\Nailuy\AppData\Local\Programs\Python\Python312\Lib\site-packages\rombuster-1.0.0-py3.12.egg\rombuster\__main__.py", line 28, in <module>
    from pex.string import String
ModuleNotFoundError: No module named 'pex.string'

**Comment by enty8080** [comment]
It does not work on Windows
